name = "area_deficit"
version = "1.7.0"
defaultTargets = ["Solution", "Challenge"]

[[require]]
name = "complexApproximation"
path = "dependencies/ComplexApproximation"

[[require]]
name = "eremenkosConjecture"
path = "dependencies/EremenkosConjecture"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[require]]
name = "functionTheory"
path = "dependencies/FunctionTheory"

[[require]]
name = "complexDynamics"
path = "dependencies/ComplexDynamics"

[[lean_lib]]
name = "BoundedWanderingDomains"
roots = ["BoundedWanderingDomains.All"]
globs = ["BoundedWanderingDomains.+"]

[[lean_lib]]
name = "RiemannDynamics"
roots = ["RiemannDynamics.BoundedWanderingSolution"]
globs = ["RiemannDynamics.+"]

[[lean_lib]]
name = "RMT4"

[[lean_lib]]
name = "EremenkoLyubichConstant"

[[lean_lib]]
name = "Ray"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "Legacy"
roots = ["Legacy.Challenge", "Legacy.Solution", "Legacy.SingularLimitsChallenge", "Legacy.SingularLimitsSolution"]
globs = ["Legacy.+"]

[[lean_lib]]
name = "Research"
roots = ["Research.SurfaceResearch", "Research.NewResults"]
globs = ["Research.+"]
