/- Uniform compact chart gain for arbitrary open subdomains. -/
import BoundedWanderingDomains.Surfaces.CompactChartPatches
import BoundedWanderingDomains.Surfaces.GainFatou
import BoundedWanderingDomains.Surfaces.DomainCompactGain
import BoundedWanderingDomains.Surfaces.DomainRemoteArea
import BoundedWanderingDomains.Surfaces.CompactFiniteRemoval
import BoundedWanderingDomains.Surfaces.UniformFiniteRemoval
import BoundedWanderingDomains.Surfaces.FiniteModelArea
