module

public import Legacy.Solution
public import BoundedWanderingDomains.AreaDeficit
public import BoundedWanderingDomains.TrappedFilling
public import BoundedWanderingDomains.EventualCompactDiscs
public import BoundedWanderingDomains.ShrinkingChartDiscs

@[expose] public section

#print axioms BoundedWanderingDomains.no_local_bounded_wandering_domains
#print axioms BoundedWanderingDomains.no_bounded_wandering_domains_transcendental_entire
#print axioms AreaDeficit.fatou_orbit_eq_trapped_components
#print axioms AreaDeficit.trapped_component_injOn
#print axioms AreaDeficit.bounded_region_subset_trapped_interior

#print axioms AreaDeficit.trapped_closed_disc_no_bounded_complement
#print axioms AreaDeficit.bounded_fatou_orbit_simplyConnected
#print axioms EremenkosConjecture.isSimplyConnected_component_interior_of_noBoundedComplementComponents

#print axioms AreaDeficit.FinitePunctureMetricInput.no_wandering_chart_orbit_with_eventual_compact_discs
#print axioms AreaDeficit.disjoint_bounded_chart_discs_shrink
#print axioms AreaDeficit.chart_discs_eventually_in_fixed_closedBall

#print axioms AreaDeficit.bounded_point_mem_trapped_interior
#print axioms AreaDeficit.trapped_ball_interior_eq_closed
#print axioms AreaDeficit.injOn_of_power_coordinate
#print axioms AreaDeficit.eventually_injOn_shrinking_chart_discs
#print axioms AreaDeficit.FinitePunctureMetricInput.no_wandering_fatou_orbit_of_bounded_point

#print axioms BoundedWanderingDomains.wandering_orbit_locallyUniform_infty
#print axioms BoundedWanderingDomains.wandering_orbit_pointwise_spherical_singular_derivedSet
#print axioms BoundedWanderingDomains.wandering_orbit_locallyUniform_spherical_singular_derivedSet
#print axioms BoundedWanderingDomains.local_wandering_orbit_locallyUniform_singular_derivedSet
