import Solution
import AreaDeficit

#print axioms BoundedWanderingDomains.no_local_bounded_wandering_domains
#print axioms BoundedWanderingDomains.no_bounded_wandering_domains_transcendental_entire
#print axioms AreaDeficit.fatou_orbit_eq_trapped_components

