import NewResults
import Solution

#print axioms AreaDeficit.uniform_compact_gain_sphere
#print axioms AreaDeficit.sphere_finite_puncture_gain_le_two_pi_mul_card
#print axioms AreaDeficit.uniform_compact_finite_gain_plane
#print axioms BoundedWanderingDomains.wandering_orbit_subsequence_spherical_singular_derivedSet
#print axioms BoundedWanderingDomains.wandering_orbit_locallyUniform_spherical_singular_derivedSet
#print axioms BoundedWanderingDomains.no_escaping_wandering_orbit_of_classB
#print axioms BoundedWanderingDomains.no_local_bounded_wandering_domains
#print axioms BoundedWanderingDomains.no_bounded_wandering_domains_transcendental_entire

#print axioms BoundedWanderingDomains.local_wandering_orbit_subsequence_spherical_singular_derivedSet
#print axioms BoundedWanderingDomains.local_wandering_orbit_locallyUniform_singular_derivedSet
#print axioms ComplexDynamics.singularValuesOn_congr
