import Solution

#print axioms BoundedWanderingDomains.wandering_domain_has_locally_uniform_escaping_subsequence
#print axioms MeromorphicDynamics.wandering_domain_has_locally_uniform_escaping_subsequence
#print axioms SurfaceDynamics.wandering_component_orbit_not_compactly_contained
#print axioms SurfaceDynamics.positive_area_wandering_saturation_not_compactly_contained
#print axioms BoundedWanderingDomains.wandering_orbit_accumulates_on_derived_singular_values
#print axioms SurfaceDynamics.wandering_orbit_has_escaping_or_derived_singular_subsequence

#print axioms BoundedWanderingDomains.no_bounded_wandering_domains_transcendental_entire

#print axioms BoundedWanderingDomains.no_wandering_domains_transcendental_entire_finite_singularValues
#print axioms SurfaceDynamics.no_wandering_domains_compact
#print axioms SurfaceDynamics.no_wandering_domains_rational

#print axioms SurfaceDynamics.compact_wandering_orbit_accumulates_on_derived_singular_values
#print axioms SurfaceDynamics.almost_every_wandering_point_has_source_escaping_subsequence
#print axioms SurfaceDynamics.positive_area_wandering_saturation_not_compactly_contained_away_from_derived
#print axioms SurfaceDynamics.almost_every_wandering_point_has_escaping_or_derived_singular_subsequence

#print axioms SurfaceDynamics.no_wandering_domains_finite_type
#print axioms MeromorphicDynamics.no_wandering_domains_transcendental_meromorphic_finite_singularValues
