import SurfaceResearch

#print axioms AreaDeficit.Surfaces.DiscCover.density_nested_subdomains
#print axioms AreaDeficit.Surfaces.DiscCover.density_sequence_bounded_by_subdomain
#print axioms AreaDeficit.Surfaces.normal_lift_limit_maps_disc
#print axioms AreaDeficit.Surfaces.DiscCover.density_tendsto_of_dense_punctures
#print axioms RiemannDynamics.exists_hyperbolicMetric
#print axioms RiemannDynamics.exists_hyperbolicMetric_of_diffeomorph
#print axioms AreaDeficit.Surfaces.exists_smooth_separating_cutoff
#print axioms AreaDeficit.Surfaces.exists_smooth_separating_cutoff_mfderiv
#print axioms AreaDeficit.Surfaces.hasCompactSupport_chartLaplacian
#print axioms AreaDeficit.Surfaces.disjoint_tsupport_chartLaplacian_of_const_near
#print axioms SurfaceDynamics.tendsto_infty_iff_leaves_compacts
#print axioms SurfaceDynamics.escape_or_convergent_subsequence
#print axioms SurfaceDynamics.LocalMap.iterate_eq_some_orbit
#print axioms SurfaceDynamics.LocalMap.continuous_orbit
#print axioms SurfaceDynamics.LocalMap.omega_subset_source
#print axioms SurfaceDynamics.LocalMap.isClosed_singularValues
#print axioms AreaDeficit.Surfaces.unitDisc_simplyConnected
#print axioms AreaDeficit.Surfaces.exists_eventually_large_area
#print axioms AreaDeficit.Surfaces.no_uniform_finite_area_bound

#print axioms AreaDeficit.Surfaces.isManifold_real_of_complex
#print axioms AreaDeficit.Surfaces.exists_surface_separating_cutoff

#print axioms AreaDeficit.Surfaces.mdifferentiableOn_symm
#print axioms AreaDeficit.Surfaces.mdifferentiable_lift
#print axioms AreaDeficit.Surfaces.exists_holomorphic_lift
#print axioms AreaDeficit.Surfaces.planeExtension_deriv_comp
#print axioms AreaDeficit.Surfaces.disc_schwarz_at
#print axioms AreaDeficit.Surfaces.unitDisc_schwarz
#print axioms AreaDeficit.Surfaces.coordinate_deriv_ne_zero
#print axioms AreaDeficit.Surfaces.DiscCover.fibreDensity_eq
#print axioms AreaDeficit.Surfaces.DiscCover.density_independent
#print axioms AreaDeficit.Surfaces.DiscCover.density_pos
#print axioms AreaDeficit.Surfaces.DiscCover.local_density_expression
#print axioms AreaDeficit.Surfaces.DiscCover.chartDensity_contDiffAt
#print axioms AreaDeficit.Surfaces.DiscCover.chartDensity_curvature

#print axioms AreaDeficit.Surfaces.coordinate_deriv_comp
#print axioms AreaDeficit.Surfaces.DiscCover.density_schwarz_disc
#print axioms AreaDeficit.Surfaces.DiscCover.density_schwarz
#print axioms AreaDeficit.Surfaces.DiscCover.density_coordinate_change
#print axioms AreaDeficit.Surfaces.DiscCover.chartArea_coordinate_change
#print axioms AreaDeficit.Surfaces.DiscCover.coordinateArea_eq
#print axioms AreaDeficit.Surfaces.DiscCover.localArea_overlap
#print axioms AreaDeficit.Surfaces.exists_chartPartition
#print axioms AreaDeficit.Surfaces.DiscCover.areaUsing_independent
#print axioms AreaDeficit.Surfaces.DiscCover.hyperbolicArea_apply_chart
#print axioms AreaDeficit.Surfaces.DiscCover.hyperbolicArea_independent
#print axioms AreaDeficit.Surfaces.DiscCover.density_subdomain_le
#print axioms AreaDeficit.Surfaces.DiscCover.chartLogRatio_contDiffAt
#print axioms AreaDeficit.Surfaces.DiscCover.chartLogRatio_laplacian
#print axioms AreaDeficit.Surfaces.DiscCover.chartLogRatio_laplacian_nonneg
#print axioms AreaDeficit.Surfaces.DiscCover.density_ratio_coordinate_independent
#print axioms AreaDeficit.Surfaces.DiscCover.one_le_densityRatio

#print axioms AreaDeficit.Surfaces.DiscCover.densityRatio_continuous
#print axioms AreaDeficit.Surfaces.DiscCover.hyperbolicArea_setLIntegral
#print axioms AreaDeficit.Surfaces.DiscCover.areaGain_coordinate_formula
#print axioms AreaDeficit.Surfaces.DiscCover.chart_gain_cutoff
#print axioms AreaDeficit.Surfaces.DiscCover.compact_uniform_disc_avoidance
#print axioms AreaDeficit.Surfaces.DiscCover.density_extremal_disc
#print axioms AreaDeficit.Surfaces.DiscCover.densityRatio_le_of_disc_avoidance
#print axioms AreaDeficit.Surfaces.DiscCover.remote_densityRatio_bound
