"""Regenerate the own-source module index and exact direct-import graph.

Run from any directory with Python 3. No third-party packages are required.
Vendored/dependency internals are not indexed as original project material.
"""
from pathlib import Path
import json
import os
import re

ROOT = Path(__file__).resolve().parents[1]
SKIP = {'.git', '.lake', 'vendor', 'verification', 'scripts'}


def collect():
    records = []
    for directory, folders, filenames in os.walk(ROOT, followlinks=False):
        folders[:] = sorted(f for f in folders if f not in SKIP and
                            not (Path(directory)/f).is_symlink())
        for filename in sorted(filenames):
            if not filename.endswith('.lean'):
                continue
            p = Path(directory)/filename
            relative = p.relative_to(ROOT).as_posix()
            text = p.read_text(encoding='utf-8-sig')
            imports = re.findall(r'^(?:public )?import\s+([\w.]+)', text, re.M)
            declarations=[]
            # Names are displayed as written in source, not reconstructed by
            # guessing Lean's namespace/section elaboration rules.
            for m in re.finditer(r'^(?:@\[[^\n]*\]\s*)?(?:noncomputable\s+)?'
                                 r'(theorem|lemma|def|abbrev|structure|inductive)\s+([^\s:({]+)', text, re.M):
                declarations.append({'kind':m[1], 'name':m[2],
                                     'line':text.count('\n',0,m.start())+1})
            title = re.search(r'/-!\s*#\s+([^\n]+)',text)
            records.append({'module':relative[:-5].replace('/','.'), 'path':relative,
                            'title':title[1].strip() if title else relative[:-5].split('/')[-1],
                            'imports':imports,'declarations':declarations})
    return sorted(records,key=lambda r:r['module'])


def main():
    records=collect()
    byname={r['module']:r for r in records}
    usedby={r['module']:[] for r in records}
    for r in records:
        for imp in r['imports']:
            if imp in usedby:
                usedby[imp].append(r['module'])
    graph={'description':'Direct Lean imports, not minimal theorem dependencies. Own source only; external imports retained as labelled leaves.',
           'generator':'scripts/update-map.py','modules':records,
           'edges':[{'from':imp,'to':r['module'],'external':imp not in byname}
                    for r in records for imp in r['imports']]}
    docs=ROOT/'docs'
    docs.mkdir(exist_ok=True)
    (docs/'import-graph.json').write_text(json.dumps(graph,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    count=sum(len(r['declarations']) for r in records)
    lines=['# Complete module index','',
           '[Main results](../MAIN_RESULTS.md) · [Proof map](../PROOF_MAP.md) · [Classical results](../CLASSICAL_RESULTS.md)','',
           f'{len(records)} own-source modules; {count} named public theorem/definition declarations detected. Names are shown as written in source. Private helpers, instances, generated declarations and vendored internals are not counted.','',
           'Generated by `python scripts/update-map.py`. The [JSON graph](import-graph.json) contains all direct imports, including external imports. Import edges can be broader than the actual dependencies of one theorem.','',
           '| Module | Topic | Public declarations |','| --- | --- | ---: |']
    for r in records:
        lines.append(f"| [{r['module']}](../{r['path']}) | {r['title'].replace('|','/')} | {len(r['declarations'])} |")
    for r in records:
        lines += ['',f"## {r['module']}",'',f"[{r['title']}](../{r['path']})",'']
        local=[f"[{i}](../{byname[i]['path']})" for i in r['imports'] if i in byname]
        ext=[f'`{i}`' for i in r['imports'] if i not in byname]
        users=[f"[{i}](../{byname[i]['path']})" for i in usedby[r['module']]]
        lines += ['**Imports here:** '+(', '.join(local) if local else 'None.'),'',
                  '**Imported foundations / sibling modules:** '+(', '.join(ext) if ext else 'None.'),'',
                  '**Used directly by:** '+(', '.join(users) if users else 'No own-source module; may be a root or separately built target.'),'']
        if r['declarations']:
            lines += ['<details>','<summary>Declarations with direct source links</summary>','']
            for d in r['declarations']:
                lines.append(f"- {d['kind']} [{d['name']}](../{r['path']}#L{d['line']})")
            lines += ['','</details>']
    (docs/'MODULE_INDEX.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps({'project':ROOT.name,'modules':len(records),'declarations':count}))


if __name__=='__main__':
    main()
