module

public import ComplexApproximation.Topology.FilledContinua
public import Runge
public import ComplexApproximation.MainTheorems
public import ComplexApproximation.Topology.Nonseparation
public import ComplexApproximation.Topology.HorizontalSets
public import ComplexApproximation.Topology.ArakelianHomeomorphism
public import ComplexApproximation.Topology.StripArakelian
public import ComplexApproximation.Topology.HalfStripBands
public import ComplexApproximation.HalfStripExtension
public import ComplexApproximation.HalfStripApproximation
public import ComplexApproximation.HalfStripMargins
public import ComplexApproximation.HalfStripTail
public import ComplexApproximation.HorizontalStripExtension
public import ComplexApproximation.Conformal.KernelConvergence

public import ComplexApproximation.Topology.FillingStraightChannels
public import ComplexApproximation.Topology.FillingInterior
public import ComplexApproximation.Topology.FillingCoordinateBounds

public import ComplexApproximation.Topology.ArakelianElementaryGeometry

public import ComplexApproximation.Topology.FillingDecreasingIntersection

public import ComplexApproximation.Topology.NestedBandNonseparation

public import ComplexApproximation.Topology.StraightTailComplement

public import ComplexApproximation.Topology.StraightBandArakelian

public import ComplexApproximation.Topology.LocalHomeomorphNonseparation

public import ComplexApproximation.Topology.HomeomorphicTail

public import ComplexApproximation.Topology.ConformalArakelian

public import ComplexApproximation.Topology.FullCompactSets
public import ComplexApproximation.Topology.EscapingFullFamily
public import ComplexApproximation.Topology.FullSubsetSeparation

public import ComplexApproximation.Topology.TwoPointNonseparation
public import ComplexApproximation.Topology.FullFamilyFilling
public import ComplexApproximation.Topology.FullSeparatedExhaustion
public import ComplexApproximation.Topology.FullNeighborhoodFamily

@[expose] public section

/-!
# Complex approximation theory

The existing Runge imports and namespace remain available. The public statement
gallery also exports neighbourhood-holomorphic Arakelian approximation and
the smooth compact-support Cauchy–Pompeiu formula.
-/
